{
 "title": "Kubernetes cluster metrics",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Number of nodes",
   "type": "stat",
   "description": "Number of active Kubernetes nodes in the cluster",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(node_os_info)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total pods",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(kube_pod_status_phase)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Running pods",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{phase=\"Running\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pending pods",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{phase=\"Pending\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failed pods",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{phase=\"Failed\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Ratio of Used memory",
   "type": "gauge",
   "description": "Total Used memory across all nodes",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(sum (node_memory_MemTotal_bytes) - sum (node_memory_MemAvailable_bytes)) / sum (node_memory_MemTotal_bytes)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Available Memory",
   "type": "stat",
   "description": "Total Available Memory across all nodes",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum (node_memory_MemAvailable_bytes)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Memory",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total ratio of CPU usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(1-rate(node_cpu_seconds_total{mode=\"idle\", job=\"node-exporter\"}[1m])) / sum(machine_cpu_cores)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU cores used",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(1-rate(node_cpu_seconds_total{mode=\"idle\", job=\"node-exporter\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total cores",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "sum(machine_cpu_cores)", "legendFormat": "__auto" }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Percentage of Used Memory",
   "type": "timeseries",
   "description": "Used memory on each node",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum without(container,endpoint,instance,job,service,namespace,pod) (((node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes) * on(instance) group_left(nodename) (node_uname_info))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory usage (not kube-system)",
   "type": "timeseries",
   "description": "Memory usage of containers",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum without(__name__,endpoint,instance,job,metrics_path,name,service,id) (container_memory_working_set_bytes{namespace!='kube-system',container!=''})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ratio Memory usage / Memory limit (not kube-system)",
   "type": "timeseries",
   "description": "Ratio of memory usage / memory limit for non-system containers",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{namespace!='kube-system',container!=''} / on(namespace,container,pod) cluster:namespace:pod_memory:active:kube_pod_container_resource_limits{namespace!='kube-system',container!=''}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ratio Memory usage / Memory request",
   "type": "timeseries",
   "description": "Ratio of the current memory usage / memory requested",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg by(pod,namespace)(container_memory_working_set_bytes{namespace!='kube-system',container!=''}) / avg by(pod,namespace)(cluster:namespace:pod_memory:active:kube_pod_container_resource_requests{namespace!='kube-system',container!=''})",
     "legendFormat": "__auto"
    },
    { "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Memory usage (kube system)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum without(__name__,endpoint,instance,job,metrics_path,name,service,id) (container_memory_working_set_bytes{namespace='kube-system',container!=''})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "CPU utilization per node",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 - (avg by (instance) (irate(node_cpu_seconds_total{mode=\"idle\"}[10m])) * on(instance) group_left(nodename) (node_uname_info))",
     "legendFormat": "{{nodename}}"
    }
   ]
  },
  {
   "title": "CPU cores utilization per container",
   "type": "timeseries",
   "description": "Number of cores used by each container in the past 5 minutes",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "targets": [
    {
     "expr": "sum without(cpu,endpoint,id,instance,job,metrics_path,name,service) (rate(container_cpu_usage_seconds_total{namespace!='kube-system',container!=''}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ratio CPU usage / CPU limit (not kube-system)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "irate(container_cpu_usage_seconds_total{namespace!='kube-system', container!=''}[5m]) / on(namespace,pod,container)cluster:namespace:pod_cpu:active:kube_pod_container_resource_limits",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ratio CPU usage / CPU request (not kube-system)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "irate(container_cpu_usage_seconds_total{namespace!='kube-system',container!=''}[5m]) / on(namespace,pod,container)cluster:namespace:pod_cpu:active:kube_pod_container_resource_requests",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU core utilization (kube system)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
   "targets": [
    {
     "expr": "sum without(cpu,endpoint,id,instance,job,metrics_path,name,service) (rate(container_cpu_usage_seconds_total{namespace='kube-system',container!=''}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Pods", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 } },
  {
   "title": "Capacity of applications (ratio of available replicas out of specified replicas)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum without(container,endpoint,instance,job,pod,service) (kube_deployment_status_replicas_available / kube_deployment_spec_replicas)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Container restart rate (per container)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 63 },
   "targets": [
    {
     "expr": "sum by(container,namespace) (increase(kube_pod_container_status_restarts_total[1h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate of OOM events per container",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 71 },
   "targets": [
    {
     "expr": "sum by(container,image,namespace) (rate(container_oom_events_total[1h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Persistent Volumes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 79 } },
  {
   "title": "Persistent Volume Available space",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum without(__name__,endpoint,instance,job,metrics_path,service) (kubelet_volume_stats_available_bytes{namespace!='kube-system'})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Percentage of Used space",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum without(endpoint,instance,job,metrics_path,service) ((kubelet_volume_stats_capacity_bytes{namespace!='kube-system'} - kubelet_volume_stats_available_bytes{namespace!='kube-system'}) / kubelet_volume_stats_capacity_bytes{namespace!='kube-system'})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PV Available inodes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 88 },
   "targets": [
    {
     "expr": "sum without(__name__,endpoint,instance,job,metrics_path,service) (kubelet_volume_stats_inodes_free{namespace!='kube-system'})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Percentage of used inodes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum without(endpoint,instance,job,metrics_path,service) (kubelet_volume_stats_inodes_used{namespace!='kube-system'} / kubelet_volume_stats_inodes_free{namespace!='kube-system'})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Filesystems", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 96 } },
  {
   "title": "Top 10 of used space percentage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum without(container,endpoint,instance,job) (topk(10, (node_filesystem_size_bytes{container!='',mountpoint=\"/\",fstype!=\"rootfs\"} - node_filesystem_avail_bytes{container!='',mountpoint=\"/\",fstype!=\"rootfs\"}) / node_filesystem_size_bytes{container!='',mountpoint=\"/\",fstype!=\"rootfs\"}) * on(instance) group_left(nodename) (node_uname_info))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 105 } },
  {
   "title": "Received bandwidth per node",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 106 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum without(instance) (sum(rate(node_network_receive_bytes_total[1m])) by (instance) * on(instance) group_left(nodename) (node_uname_info))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transmitted bandwidth per node",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 106 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum without(instance) (sum(rate(node_network_transmit_bytes_total[1m])) by (instance) * on(instance) group_left(nodename) (node_uname_info))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Received error ratio",
   "type": "timeseries",
   "description": "Rate of received errors out of rate of received packets",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 114 },
   "targets": [
    {
     "expr": "sum without(instance) ((sum(rate(node_network_receive_errs_total[1m])) by(instance) / sum(rate(node_network_receive_packets_total[1m])) by (instance)) * on(instance) group_left(nodename) (node_uname_info))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transmitted error ratio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 114 },
   "targets": [
    {
     "expr": "sum without(instance) ((sum(rate(node_network_transmit_errs_total[1m])) by(instance) / sum(rate(node_network_transmit_packets_total[1m])) by (instance)) * on(instance) group_left(nodename) (node_uname_info))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Received bandwidth per namespace",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 122 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_bytes_total[$__rate_interval])) by (namespace)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transmitted bandwidth per namespace",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 122 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(irate(container_network_transmit_bytes_total[$__rate_interval])) by (namespace)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate of dropped received packets per namespace",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 130 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum by(namespace) (rate(container_network_receive_packets_dropped_total[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate of dropped transmitted packets per namespace",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 130 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum (rate(container_network_transmit_packets_dropped_total[5m])) by (namespace)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Nginx - Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 138 } },
  {
   "title": "Requests throughput",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 139 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(exported_service,host,ingress) (irate(nginx_ingress_controller_requests[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request durations by ingress target",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 146 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (exported_namespace,exported_service,host,ingress) (irate(nginx_ingress_controller_request_duration_seconds_sum[5m])) / sum by (exported_namespace,exported_service,host,ingress) (irate(nginx_ingress_controller_request_duration_seconds_count[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request response times by ingress target",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 146 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (exported_namespace,exported_service,host,ingress) (irate(nginx_ingress_controller_response_duration_seconds_sum[5m])) / sum by (exported_namespace,exported_service,host,ingress) (irate(nginx_ingress_controller_response_duration_seconds_count[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests duration by ingress, method and status code",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 154 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (exported_namespace,host,ingress,path,method,status) (irate(nginx_ingress_controller_request_duration_seconds_sum[5m])) / sum by (exported_namespace,host,ingress,path,method,status) (irate(nginx_ingress_controller_request_duration_seconds_count[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Response times by ingress, method and status code",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 154 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (exported_namespace,host,ingress,path,method,status) (irate(nginx_ingress_controller_response_duration_seconds_sum[5m])) / sum by (exported_namespace,host,ingress,path,method,status) (irate(nginx_ingress_controller_response_duration_seconds_count[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error ratio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 162 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(exported_namespace,exported_service,host,ingress,path,status) (rate(nginx_ingress_controller_requests{status=~'5..'}[1m])) / sum by(exported_namespace,exported_service,host,ingress,path,status) (rate(nginx_ingress_controller_requests[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Backend Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 170 } },
  {
   "title": "Average Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 171 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (app,container) (irate(http_request_duration_seconds_sum{namespace='backend'}[1m])) / sum by (app,container) (irate(http_request_duration_seconds_count{namespace='backend'}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 171 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(namespace,container) (irate(http_request_total{namespace='backend'}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Latency - per route, method and code",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 179 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (app,container,method,route,code) (irate(http_request_duration_seconds_sum{namespace='backend'}[1m])) / sum by (app,container,method,route,code) (irate(http_request_duration_seconds_count{namespace='backend'}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency (95 percentile)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 179 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum without(app,job,namespace,container) (histogram_quantile(0.95, sum (irate(http_request_duration_seconds_bucket{namespace='backend'}[1m])) by (app,container,job,le,namespace,pod,route)))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 187 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum without(container,namespace) (sum by(namespace,container,route,method) (rate(http_request_total{namespace='backend'}[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 187 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum without(container,namespace) (sum by(namespace,container,method,route) (irate(http_request_total{namespace='backend',code=~\"5..\"}[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error ratio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 195 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(namespace,container,method,route) (irate(http_request_total{namespace='backend',code=~\"5..\"}[1m])) / sum by(namespace,container,method,route) (irate(http_request_total{namespace='backend'}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Backend Latency - Standard Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 203 }
  },
  {
   "title": "Average Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 204 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by (app,container) (irate(standard_http_request_duration_seconds_sum{namespace='backend'}[1m])) / sum by (app,container) (irate(standard_http_request_duration_seconds_count{namespace='backend'}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Latency - Per route, method and code",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 204 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by (app,container,method,route,code) (irate(standard_http_request_duration_seconds_sum{namespace='backend'}[1m])) / sum by (app,container,method,route,code) (irate(standard_http_request_duration_seconds_count{namespace='backend'}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency - 95 percentile",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 212 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum without(app,job,namespace,container) (histogram_quantile(0.95, sum (irate(standard_http_request_duration_seconds_bucket{namespace='backend'}[1m])) by (app,container,job,le,namespace,pod,route)))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}